[build]
  command = "mkdir -p boutiquemg_reservas && cp -r * boutiquemg_reservas/"
  publish = "boutiquemg_reservas"
  functions = "functions"

# Especifica explícitamente que es un proyecto PHP
[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "16" # Solo para evitar advertencias
  NPM_FLAGS = "--prefix nonexistent" # Truco para evitar instalación de paquetes

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
