[build]
  # No build command needed for pure PHP projects
  publish = "boutiquemg_reservas"
  functions = "functions"

[build.environment]
  PHP_VERSION = "8.2"
  NPM_FLAGS = "--version"  # Prevents Node.js dependency errors

# Required for PHP routing - all requests go to index.php
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.whatsapp.com;
      img-src 'self' data: https:;
      script-src 'self' 'unsafe-inline' https://*.whatsapp.com;
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https://*.whatsapp.com;
    """

# Environment variables (optional)
[context.production.environment]
  WHATSAPP_NUMBER = "+50587010851"
  SITE_TITLE = "Boutique MG Reservas"
