[build]
  publish = "boutiquemg_reservas"
  command = "echo 'Skipping build for PHP project'"

[build.environment]
  PHP_VERSION = "8.2"
  NPM_FLAGS = "--version"  # Truco para evitar errores de Node

# Redirección para enrutamiento PHP
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Cabeceras de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://*.whatsapp.com"
