[build]
  publish = "boutiquemg_reservas"
  functions = "functions"

# Configuración específica para PHP
[build.environment]
  PHP_VERSION = "8.2"
  NPM_FLAGS = "--version"  # Evita errores de Node.js

# Redirecciones para el enrutamiento PHP
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Cabeceras de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' https://*.whatsapp.com"

# Configuración del procesamiento de PHP
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  framework = "#custom"  # Desactiva detección automática de frameworks
  command = "echo 'Servidor PHP listo'"
