[build]
  publish = "boutiquemg_reservas"
  command = "echo 'Skipping build for PHP project'"

[build.environment]
  PHP_VERSION = "8.2"
  NPM_FLAGS = "--version"  # Dummy command to avoid Node.js errors

# Redirects for PHP routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://*.whatsapp.com"

# Potential improvements added below

# Add Strict-Transport-Security for enhanced HTTPS security
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Specify a Referrer-Policy header for better control over referrer information
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
